/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_benews_BsonBridge */

#ifndef _Included_org_benews_BsonBridge
#define _Included_org_benews_BsonBridge
#ifdef __cplusplus
extern "C" {
#endif
#undef org_benews_BsonBridge_BSON_TYPE_TEXT
#define org_benews_BsonBridge_BSON_TYPE_TEXT 0L
/*
 * Class:     org_benews_BsonBridge
 * Method:    serialize
 * Signature: (Ljava/lang/String;[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_benews_BsonBridge_serialize
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     org_benews_BsonBridge
 * Method:    getToken
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_benews_BsonBridge_getToken
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
