/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_be_news_BsonBridge */

#ifndef _Included_org_be_news_BsonBridge
#define _Included_org_be_news_BsonBridge
#ifdef __cplusplus
extern "C" {
#endif
#undef org_be_news_BsonBridge_BSON_TYPE_TEXT
#define org_be_news_BsonBridge_BSON_TYPE_TEXT 0L
/*
 * Class:     org_be_news_BsonBridge
 * Method:    serialize2
 * Signature: (Ljava/lang/String;II[B)I
 */
JNIEXPORT jint JNICALL Java_org_be_1news_BsonBridge_serialize2
  (JNIEnv *, jclass, jstring, jint, jint, jbyteArray);

/*
 * Class:     org_be_news_BsonBridge
 * Method:    getGreatings
 * Signature: (Ljava/lang/String;II[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_be_1news_BsonBridge_getGreatings
  (JNIEnv *, jclass, jstring, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
